apiVersion: v1
kind: Pod
metadata:
  name: alpine-sa
  labels:
    app: alpine-sa
spec:
  serviceAccountName: mysa
  containers:
    - name: alpine
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "[INFO] Starting container with ServiceAccount: mysa";
          sleep 3600;
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
        requests:
          memory: "32Mi"
          cpu: "100m"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
