apiVersion: v1
kind: Pod
metadata:
  name: alpine-2-containers
  labels:
    app: alpine-2-containers
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "[alpine] Hello from container";
          sleep 3600;
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
