apiVersion: v1
kind: Pod
metadata:
  name: alpine-2-containers
  labels:
    app: alpine-2-containers
spec:
  containers:
    - name: alpine1
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "[alpine1] Starting up...";
          sleep 10000;
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

    - name: alpine2
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "[alpine2] Starting up...";
          sleep 10000;
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

  dnsPolicy: ClusterFirst
  restartPolicy: Never
