apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver
  namespace: database-management
  labels:
    app: cloudbeaver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: database-management
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: cloudbeaver
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:23.2.5
          ports:
            - containerPort: 8978
          volumeMounts:
            - mountPath: /opt/cloudbeaver/workspace
              name: workspace
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 8978
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8978
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  namespace: database-management
  labels:
    app: cloudbeaver
spec:
  ports:
    - port: 8978
      targetPort: 8978
      nodePort: 30433 # Use only if NodePort is required
  selector:
    app: cloudbeaver
  type: NodePort # Change to ClusterIP if external access is not needed
