apiVersion: v1
kind: ConfigMap  
metadata:
  name: app-config 
data:
  application.properties: |
    spring.mvc.view.prefix=/pages/
    spring.mvc.view.suffix=.jsp
    spring.datasource.url = jdbc:mysql://dpt3-rds-01.cikw6aborn1z.us-east-1.rds.amazonaws.com:3306/UserDB
    spring.datasource.username = admin
    spring.datasource.password = admin12345